version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gasshuku_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  web:
    build: .
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB: gasshuku_database
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - .:/go/src/github.com/MrFuku/gasshuku

volumes:
  mysql_data:
